[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Server utils for tetsy-jsonrpc-core crate."
documentation = "https://docs.rs/tetsy-jsonrpc-server-utils/"
edition = "2018"
homepage = "https://github.com/tetcoin/tetsy-jsonrpc"
keywords = ["jsonrpc", "json-rpc", "json", "rpc", "serde"]
license = "MIT"
name = "tetsy-jsonrpc-server-utils"
repository = "https://github.com/tetcoin/tetsy-jsonrpc"
version = "14.2.0"

[dependencies]
bytes = "0.4"
globset = "0.4"
tetsy-jsonrpc-core = { version = "14.2", path = "../core" }
lazy_static = "1.1.0"
log = "0.4"
tokio = { version = "0.1.15" }
tokio-codec = { version = "0.1" }
unicase = "2.0"

[badges]
travis-ci = { repository = "tetcoin/tetsy-jsonrpc", branch = "master"}
